### ISSUE TITLE
Problem with java client

### ISSUE THREAD

**Issue by nablex** [nabu-platform/eai-module-http-reverse-proxy#1]
Somewhere in stabilizing the reverse proxy, a bug may have crept it although it is hard to say who is at fault in this particular situation. 

```java
URL url = new URL("https://nabu.be");
URLConnection openConnection = url.openConnection();
openConnection.addRequestProperty("Connection", "close");
InputStream inputStream = openConnection.getInputStream();
byte[] bytes = IOUtils.toBytes(IOUtils.wrap(inputStream));
inputStream.close();
```

If you run this code, it works. If you disable the explicit request for connection "close", it fails and hangs indefinitely.

A thread dump reveals the thread hanging on:

```
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        - locked <0x000000071ce0ec20> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        - locked <0x000000071ce0ece8> (a sun.security.ssl.AppInputStream)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x000000071ce7e1d0> (a java.io.BufferedInputStream)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3444)
        at be.nabu.utils.io.containers.bytes.InputStreamWrapper.read(InputStreamWrapper.java:29)
        at be.nabu.utils.io.containers.bytes.InputStreamWrapper.read(InputStreamWrapper.java:9)
        at be.nabu.utils.io.IOUtils.copy(IOUtils.java:215)
        at be.nabu.utils.io.IOUtils.copyBytes(IOUtils.java:194)
        at be.nabu.utils.io.IOUtils.toBytes(IOUtils.java:96)
```
Either the default http client is doing something wrong or the proxy is. Note that no other software seems to have a problem with the proxy.

The problem first presented itself with glue (which uses the default http provider for some resolves) where the workaround of asking for a close was added.

**Comment by nablex** [comment]
After some debugging, it turns out at least part of the problem was a trailing \r could sneak into the proxied responses yielding something like:

HTTP/1.1 200 OK\r\r\nX-Frame-Options: DENY\r\nContent-Type...
